import './globals.css'
import { M_PLUS_1 } from 'next/font/google'

const mplus1 = M_PLUS_1({
  subsets: ["latin"],
});




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="jp">
      <body className={mplus1.className} >
        <div className='max-w-md m-auto bg-white h-screen'>
        {children}
        </div>
        </body>
    </html>
  )
}
